/* =========================================================
   Task 4: SQL Intermediate – JOINS
   Database: MySQL
   Author: <Aman Kesarwani>
   Description:
   This file contains all final working SQL JOIN queries
   used for business analysis.
   ========================================================= */


/* =========================================================
   1. INNER JOIN
   Purpose:
   Combine orders with customer details.
   Used for sales reports and order tracking.
   ========================================================= */

SELECT
    o.order_id,
    o.order_date,
    c.customer_id,
    c.customer_name,
    c.region
FROM orders o
INNER JOIN customers c
    ON o.customer_id = c.customer_id;



/* =========================================================
   2. LEFT JOIN
   Purpose:
   Find customers who have never placed any orders.
   Used for marketing and customer re-engagement.
   ========================================================= */

SELECT
    c.customer_id,
    c.customer_name,
    c.email
FROM customers c
LEFT JOIN orders o
    ON c.customer_id = o.customer_id
WHERE o.order_id IS NULL;



/* =========================================================
   3. Revenue per Product
   Purpose:
   Calculate total revenue generated by each product.
   Helps identify top-performing SKUs.
   ========================================================= */

SELECT
    p.product_id,
    p.product_name,
    SUM(o.quantity * o.unit_price) AS total_revenue
FROM orders o
INNER JOIN products p
    ON o.product_id = p.product_id
GROUP BY p.product_id, p.product_name
ORDER BY total_revenue DESC;



/* =========================================================
   4. Category-wise Revenue
   Purpose:
   Calculate revenue distribution across product categories.
   Used for product strategy and category performance analysis.
   ========================================================= */

SELECT
    cat.category_id,
    cat.category_name,
    SUM(o.quantity * o.unit_price) AS category_revenue
FROM orders o
INNER JOIN products p
    ON o.product_id = p.product_id
INNER JOIN categories cat
    ON p.category_id = cat.category_id
GROUP BY cat.category_id, cat.category_name
ORDER BY category_revenue DESC;



/* =========================================================
   5. Business Question:
   Total sales for a specific region within a date range.
   Example: Sales in Asia between 2024-01-01 and 2024-12-31
   ========================================================= */

SELECT
    c.region,
    SUM(o.quantity * o.unit_price) AS total_sales
FROM orders o
INNER JOIN customers c
    ON o.customer_id = c.customer_id
WHERE c.region = 'Asia'
  AND o.order_date BETWEEN '2024-01-01' AND '2024-12-31'
GROUP BY c.region;



/* =========================================================
   6. Combined Detailed Sales View
   Purpose:
   Final joined dataset for CSV export.
   Used to create joined_output.csv.
   ========================================================= */

SELECT
    o.order_id,
    o.order_date,
    c.customer_name,
    c.region,
    p.product_name,
    cat.category_name,
    o.quantity,
    o.unit_price,
    (o.quantity * o.unit_price) AS total_amount
FROM orders o
INNER JOIN customers c
    ON o.customer_id = c.customer_id
INNER JOIN products p
    ON o.product_id = p.product_id
INNER JOIN categories cat
    ON p.category_id = cat.category_id
ORDER BY o.order_date DESC;
